// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: point_cloud.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "point_cloud.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace SensorMsg {

namespace {

const ::google::protobuf::Descriptor* PointXYZIT_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  PointXYZIT_reflection_ = NULL;
const ::google::protobuf::Descriptor* PointCloudXYZIT_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  PointCloudXYZIT_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_point_5fcloud_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AssignDesc_point_5fcloud_2eproto() {
  protobuf_AddDesc_point_5fcloud_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "point_cloud.proto");
  GOOGLE_CHECK(file != NULL);
  PointXYZIT_descriptor_ = file->message_type(0);
  static const int PointXYZIT_offsets_[5] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PointXYZIT, x_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PointXYZIT, y_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PointXYZIT, z_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PointXYZIT, intensity_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PointXYZIT, timestamp_),
  };
  PointXYZIT_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      PointXYZIT_descriptor_,
      PointXYZIT::default_instance_,
      PointXYZIT_offsets_,
      -1,
      -1,
      -1,
      sizeof(PointXYZIT),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PointXYZIT, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PointXYZIT, _is_default_instance_));
  PointCloudXYZIT_descriptor_ = file->message_type(1);
  static const int PointCloudXYZIT_offsets_[5] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PointCloudXYZIT, header_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PointCloudXYZIT, width_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PointCloudXYZIT, height_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PointCloudXYZIT, is_dense_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PointCloudXYZIT, points_),
  };
  PointCloudXYZIT_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      PointCloudXYZIT_descriptor_,
      PointCloudXYZIT::default_instance_,
      PointCloudXYZIT_offsets_,
      -1,
      -1,
      -1,
      sizeof(PointCloudXYZIT),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PointCloudXYZIT, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PointCloudXYZIT, _is_default_instance_));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_point_5fcloud_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      PointXYZIT_descriptor_, &PointXYZIT::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      PointCloudXYZIT_descriptor_, &PointCloudXYZIT::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_point_5fcloud_2eproto() {
  delete PointXYZIT::default_instance_;
  delete PointXYZIT_reflection_;
  delete PointCloudXYZIT::default_instance_;
  delete PointCloudXYZIT_reflection_;
}

void protobuf_AddDesc_point_5fcloud_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AddDesc_point_5fcloud_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::CommonMsg::protobuf_AddDesc_header_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\021point_cloud.proto\022\tSensorMsg\032\014header.p"
    "roto\"S\n\nPointXYZIT\022\t\n\001x\030\001 \001(\002\022\t\n\001y\030\002 \001(\002"
    "\022\t\n\001z\030\003 \001(\002\022\021\n\tintensity\030\004 \001(\r\022\021\n\ttimest"
    "amp\030\005 \001(\004\"\214\001\n\017PointCloudXYZIT\022!\n\006header\030"
    "\001 \001(\0132\021.CommonMsg.Header\022\r\n\005width\030\002 \001(\005\022"
    "\016\n\006height\030\003 \001(\005\022\020\n\010is_dense\030\004 \001(\010\022%\n\006poi"
    "nts\030\005 \003(\0132\025.SensorMsg.PointXYZITb\006proto3", 280);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "point_cloud.proto", &protobuf_RegisterTypes);
  PointXYZIT::default_instance_ = new PointXYZIT();
  PointCloudXYZIT::default_instance_ = new PointCloudXYZIT();
  PointXYZIT::default_instance_->InitAsDefaultInstance();
  PointCloudXYZIT::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_point_5fcloud_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_point_5fcloud_2eproto {
  StaticDescriptorInitializer_point_5fcloud_2eproto() {
    protobuf_AddDesc_point_5fcloud_2eproto();
  }
} static_descriptor_initializer_point_5fcloud_2eproto_;

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int PointXYZIT::kXFieldNumber;
const int PointXYZIT::kYFieldNumber;
const int PointXYZIT::kZFieldNumber;
const int PointXYZIT::kIntensityFieldNumber;
const int PointXYZIT::kTimestampFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

PointXYZIT::PointXYZIT()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:SensorMsg.PointXYZIT)
}

void PointXYZIT::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

PointXYZIT::PointXYZIT(const PointXYZIT& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:SensorMsg.PointXYZIT)
}

void PointXYZIT::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
  x_ = 0;
  y_ = 0;
  z_ = 0;
  intensity_ = 0u;
  timestamp_ = GOOGLE_ULONGLONG(0);
}

PointXYZIT::~PointXYZIT() {
  // @@protoc_insertion_point(destructor:SensorMsg.PointXYZIT)
  SharedDtor();
}

void PointXYZIT::SharedDtor() {
  if (this != default_instance_) {
  }
}

void PointXYZIT::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* PointXYZIT::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return PointXYZIT_descriptor_;
}

const PointXYZIT& PointXYZIT::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_point_5fcloud_2eproto();
  return *default_instance_;
}

PointXYZIT* PointXYZIT::default_instance_ = NULL;

PointXYZIT* PointXYZIT::New(::google::protobuf::Arena* arena) const {
  PointXYZIT* n = new PointXYZIT;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void PointXYZIT::Clear() {
// @@protoc_insertion_point(message_clear_start:SensorMsg.PointXYZIT)
#if defined(__clang__)
#define ZR_HELPER_(f) \
  _Pragma("clang diagnostic push") \
  _Pragma("clang diagnostic ignored \"-Winvalid-offsetof\"") \
  __builtin_offsetof(PointXYZIT, f) \
  _Pragma("clang diagnostic pop")
#else
#define ZR_HELPER_(f) reinterpret_cast<char*>(\
  &reinterpret_cast<PointXYZIT*>(16)->f)
#endif

#define ZR_(first, last) do {\
  ::memset(&first, 0,\
           ZR_HELPER_(last) - ZR_HELPER_(first) + sizeof(last));\
} while (0)

  ZR_(x_, timestamp_);

#undef ZR_HELPER_
#undef ZR_

}

bool PointXYZIT::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:SensorMsg.PointXYZIT)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional float x = 1;
      case 1: {
        if (tag == 13) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &x_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(21)) goto parse_y;
        break;
      }

      // optional float y = 2;
      case 2: {
        if (tag == 21) {
         parse_y:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &y_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(29)) goto parse_z;
        break;
      }

      // optional float z = 3;
      case 3: {
        if (tag == 29) {
         parse_z:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &z_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(32)) goto parse_intensity;
        break;
      }

      // optional uint32 intensity = 4;
      case 4: {
        if (tag == 32) {
         parse_intensity:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &intensity_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(40)) goto parse_timestamp;
        break;
      }

      // optional uint64 timestamp = 5;
      case 5: {
        if (tag == 40) {
         parse_timestamp:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint64, ::google::protobuf::internal::WireFormatLite::TYPE_UINT64>(
                 input, &timestamp_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:SensorMsg.PointXYZIT)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:SensorMsg.PointXYZIT)
  return false;
#undef DO_
}

void PointXYZIT::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:SensorMsg.PointXYZIT)
  // optional float x = 1;
  if (this->x() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(1, this->x(), output);
  }

  // optional float y = 2;
  if (this->y() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(2, this->y(), output);
  }

  // optional float z = 3;
  if (this->z() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(3, this->z(), output);
  }

  // optional uint32 intensity = 4;
  if (this->intensity() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(4, this->intensity(), output);
  }

  // optional uint64 timestamp = 5;
  if (this->timestamp() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt64(5, this->timestamp(), output);
  }

  // @@protoc_insertion_point(serialize_end:SensorMsg.PointXYZIT)
}

::google::protobuf::uint8* PointXYZIT::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:SensorMsg.PointXYZIT)
  // optional float x = 1;
  if (this->x() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(1, this->x(), target);
  }

  // optional float y = 2;
  if (this->y() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(2, this->y(), target);
  }

  // optional float z = 3;
  if (this->z() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(3, this->z(), target);
  }

  // optional uint32 intensity = 4;
  if (this->intensity() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(4, this->intensity(), target);
  }

  // optional uint64 timestamp = 5;
  if (this->timestamp() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt64ToArray(5, this->timestamp(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:SensorMsg.PointXYZIT)
  return target;
}

int PointXYZIT::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:SensorMsg.PointXYZIT)
  int total_size = 0;

  // optional float x = 1;
  if (this->x() != 0) {
    total_size += 1 + 4;
  }

  // optional float y = 2;
  if (this->y() != 0) {
    total_size += 1 + 4;
  }

  // optional float z = 3;
  if (this->z() != 0) {
    total_size += 1 + 4;
  }

  // optional uint32 intensity = 4;
  if (this->intensity() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->intensity());
  }

  // optional uint64 timestamp = 5;
  if (this->timestamp() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt64Size(
        this->timestamp());
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void PointXYZIT::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:SensorMsg.PointXYZIT)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const PointXYZIT* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const PointXYZIT>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:SensorMsg.PointXYZIT)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:SensorMsg.PointXYZIT)
    MergeFrom(*source);
  }
}

void PointXYZIT::MergeFrom(const PointXYZIT& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:SensorMsg.PointXYZIT)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  if (from.x() != 0) {
    set_x(from.x());
  }
  if (from.y() != 0) {
    set_y(from.y());
  }
  if (from.z() != 0) {
    set_z(from.z());
  }
  if (from.intensity() != 0) {
    set_intensity(from.intensity());
  }
  if (from.timestamp() != 0) {
    set_timestamp(from.timestamp());
  }
}

void PointXYZIT::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:SensorMsg.PointXYZIT)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void PointXYZIT::CopyFrom(const PointXYZIT& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:SensorMsg.PointXYZIT)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PointXYZIT::IsInitialized() const {

  return true;
}

void PointXYZIT::Swap(PointXYZIT* other) {
  if (other == this) return;
  InternalSwap(other);
}
void PointXYZIT::InternalSwap(PointXYZIT* other) {
  std::swap(x_, other->x_);
  std::swap(y_, other->y_);
  std::swap(z_, other->z_);
  std::swap(intensity_, other->intensity_);
  std::swap(timestamp_, other->timestamp_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata PointXYZIT::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = PointXYZIT_descriptor_;
  metadata.reflection = PointXYZIT_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// PointXYZIT

// optional float x = 1;
void PointXYZIT::clear_x() {
  x_ = 0;
}
 float PointXYZIT::x() const {
  // @@protoc_insertion_point(field_get:SensorMsg.PointXYZIT.x)
  return x_;
}
 void PointXYZIT::set_x(float value) {
  
  x_ = value;
  // @@protoc_insertion_point(field_set:SensorMsg.PointXYZIT.x)
}

// optional float y = 2;
void PointXYZIT::clear_y() {
  y_ = 0;
}
 float PointXYZIT::y() const {
  // @@protoc_insertion_point(field_get:SensorMsg.PointXYZIT.y)
  return y_;
}
 void PointXYZIT::set_y(float value) {
  
  y_ = value;
  // @@protoc_insertion_point(field_set:SensorMsg.PointXYZIT.y)
}

// optional float z = 3;
void PointXYZIT::clear_z() {
  z_ = 0;
}
 float PointXYZIT::z() const {
  // @@protoc_insertion_point(field_get:SensorMsg.PointXYZIT.z)
  return z_;
}
 void PointXYZIT::set_z(float value) {
  
  z_ = value;
  // @@protoc_insertion_point(field_set:SensorMsg.PointXYZIT.z)
}

// optional uint32 intensity = 4;
void PointXYZIT::clear_intensity() {
  intensity_ = 0u;
}
 ::google::protobuf::uint32 PointXYZIT::intensity() const {
  // @@protoc_insertion_point(field_get:SensorMsg.PointXYZIT.intensity)
  return intensity_;
}
 void PointXYZIT::set_intensity(::google::protobuf::uint32 value) {
  
  intensity_ = value;
  // @@protoc_insertion_point(field_set:SensorMsg.PointXYZIT.intensity)
}

// optional uint64 timestamp = 5;
void PointXYZIT::clear_timestamp() {
  timestamp_ = GOOGLE_ULONGLONG(0);
}
 ::google::protobuf::uint64 PointXYZIT::timestamp() const {
  // @@protoc_insertion_point(field_get:SensorMsg.PointXYZIT.timestamp)
  return timestamp_;
}
 void PointXYZIT::set_timestamp(::google::protobuf::uint64 value) {
  
  timestamp_ = value;
  // @@protoc_insertion_point(field_set:SensorMsg.PointXYZIT.timestamp)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int PointCloudXYZIT::kHeaderFieldNumber;
const int PointCloudXYZIT::kWidthFieldNumber;
const int PointCloudXYZIT::kHeightFieldNumber;
const int PointCloudXYZIT::kIsDenseFieldNumber;
const int PointCloudXYZIT::kPointsFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

PointCloudXYZIT::PointCloudXYZIT()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:SensorMsg.PointCloudXYZIT)
}

void PointCloudXYZIT::InitAsDefaultInstance() {
  _is_default_instance_ = true;
  header_ = const_cast< ::CommonMsg::Header*>(&::CommonMsg::Header::default_instance());
}

PointCloudXYZIT::PointCloudXYZIT(const PointCloudXYZIT& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:SensorMsg.PointCloudXYZIT)
}

void PointCloudXYZIT::SharedCtor() {
    _is_default_instance_ = false;
  _cached_size_ = 0;
  header_ = NULL;
  width_ = 0;
  height_ = 0;
  is_dense_ = false;
}

PointCloudXYZIT::~PointCloudXYZIT() {
  // @@protoc_insertion_point(destructor:SensorMsg.PointCloudXYZIT)
  SharedDtor();
}

void PointCloudXYZIT::SharedDtor() {
  if (this != default_instance_) {
    delete header_;
  }
}

void PointCloudXYZIT::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* PointCloudXYZIT::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return PointCloudXYZIT_descriptor_;
}

const PointCloudXYZIT& PointCloudXYZIT::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_point_5fcloud_2eproto();
  return *default_instance_;
}

PointCloudXYZIT* PointCloudXYZIT::default_instance_ = NULL;

PointCloudXYZIT* PointCloudXYZIT::New(::google::protobuf::Arena* arena) const {
  PointCloudXYZIT* n = new PointCloudXYZIT;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void PointCloudXYZIT::Clear() {
// @@protoc_insertion_point(message_clear_start:SensorMsg.PointCloudXYZIT)
#if defined(__clang__)
#define ZR_HELPER_(f) \
  _Pragma("clang diagnostic push") \
  _Pragma("clang diagnostic ignored \"-Winvalid-offsetof\"") \
  __builtin_offsetof(PointCloudXYZIT, f) \
  _Pragma("clang diagnostic pop")
#else
#define ZR_HELPER_(f) reinterpret_cast<char*>(\
  &reinterpret_cast<PointCloudXYZIT*>(16)->f)
#endif

#define ZR_(first, last) do {\
  ::memset(&first, 0,\
           ZR_HELPER_(last) - ZR_HELPER_(first) + sizeof(last));\
} while (0)

  ZR_(width_, height_);
  if (GetArenaNoVirtual() == NULL && header_ != NULL) delete header_;
  header_ = NULL;
  is_dense_ = false;

#undef ZR_HELPER_
#undef ZR_

  points_.Clear();
}

bool PointCloudXYZIT::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:SensorMsg.PointCloudXYZIT)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional .CommonMsg.Header header = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_header()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(16)) goto parse_width;
        break;
      }

      // optional int32 width = 2;
      case 2: {
        if (tag == 16) {
         parse_width:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &width_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(24)) goto parse_height;
        break;
      }

      // optional int32 height = 3;
      case 3: {
        if (tag == 24) {
         parse_height:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &height_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(32)) goto parse_is_dense;
        break;
      }

      // optional bool is_dense = 4;
      case 4: {
        if (tag == 32) {
         parse_is_dense:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &is_dense_)));

        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(42)) goto parse_points;
        break;
      }

      // repeated .SensorMsg.PointXYZIT points = 5;
      case 5: {
        if (tag == 42) {
         parse_points:
          DO_(input->IncrementRecursionDepth());
         parse_loop_points:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtualNoRecursionDepth(
                input, add_points()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(42)) goto parse_loop_points;
        input->UnsafeDecrementRecursionDepth();
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:SensorMsg.PointCloudXYZIT)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:SensorMsg.PointCloudXYZIT)
  return false;
#undef DO_
}

void PointCloudXYZIT::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:SensorMsg.PointCloudXYZIT)
  // optional .CommonMsg.Header header = 1;
  if (this->has_header()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, *this->header_, output);
  }

  // optional int32 width = 2;
  if (this->width() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(2, this->width(), output);
  }

  // optional int32 height = 3;
  if (this->height() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(3, this->height(), output);
  }

  // optional bool is_dense = 4;
  if (this->is_dense() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(4, this->is_dense(), output);
  }

  // repeated .SensorMsg.PointXYZIT points = 5;
  for (unsigned int i = 0, n = this->points_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      5, this->points(i), output);
  }

  // @@protoc_insertion_point(serialize_end:SensorMsg.PointCloudXYZIT)
}

::google::protobuf::uint8* PointCloudXYZIT::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:SensorMsg.PointCloudXYZIT)
  // optional .CommonMsg.Header header = 1;
  if (this->has_header()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        1, *this->header_, false, target);
  }

  // optional int32 width = 2;
  if (this->width() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(2, this->width(), target);
  }

  // optional int32 height = 3;
  if (this->height() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(3, this->height(), target);
  }

  // optional bool is_dense = 4;
  if (this->is_dense() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(4, this->is_dense(), target);
  }

  // repeated .SensorMsg.PointXYZIT points = 5;
  for (unsigned int i = 0, n = this->points_size(); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        5, this->points(i), false, target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:SensorMsg.PointCloudXYZIT)
  return target;
}

int PointCloudXYZIT::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:SensorMsg.PointCloudXYZIT)
  int total_size = 0;

  // optional .CommonMsg.Header header = 1;
  if (this->has_header()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->header_);
  }

  // optional int32 width = 2;
  if (this->width() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->width());
  }

  // optional int32 height = 3;
  if (this->height() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->height());
  }

  // optional bool is_dense = 4;
  if (this->is_dense() != 0) {
    total_size += 1 + 1;
  }

  // repeated .SensorMsg.PointXYZIT points = 5;
  total_size += 1 * this->points_size();
  for (int i = 0; i < this->points_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->points(i));
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void PointCloudXYZIT::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:SensorMsg.PointCloudXYZIT)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const PointCloudXYZIT* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const PointCloudXYZIT>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:SensorMsg.PointCloudXYZIT)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:SensorMsg.PointCloudXYZIT)
    MergeFrom(*source);
  }
}

void PointCloudXYZIT::MergeFrom(const PointCloudXYZIT& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:SensorMsg.PointCloudXYZIT)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  points_.MergeFrom(from.points_);
  if (from.has_header()) {
    mutable_header()->::CommonMsg::Header::MergeFrom(from.header());
  }
  if (from.width() != 0) {
    set_width(from.width());
  }
  if (from.height() != 0) {
    set_height(from.height());
  }
  if (from.is_dense() != 0) {
    set_is_dense(from.is_dense());
  }
}

void PointCloudXYZIT::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:SensorMsg.PointCloudXYZIT)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void PointCloudXYZIT::CopyFrom(const PointCloudXYZIT& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:SensorMsg.PointCloudXYZIT)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PointCloudXYZIT::IsInitialized() const {

  return true;
}

void PointCloudXYZIT::Swap(PointCloudXYZIT* other) {
  if (other == this) return;
  InternalSwap(other);
}
void PointCloudXYZIT::InternalSwap(PointCloudXYZIT* other) {
  std::swap(header_, other->header_);
  std::swap(width_, other->width_);
  std::swap(height_, other->height_);
  std::swap(is_dense_, other->is_dense_);
  points_.UnsafeArenaSwap(&other->points_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata PointCloudXYZIT::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = PointCloudXYZIT_descriptor_;
  metadata.reflection = PointCloudXYZIT_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// PointCloudXYZIT

// optional .CommonMsg.Header header = 1;
bool PointCloudXYZIT::has_header() const {
  return !_is_default_instance_ && header_ != NULL;
}
void PointCloudXYZIT::clear_header() {
  if (GetArenaNoVirtual() == NULL && header_ != NULL) delete header_;
  header_ = NULL;
}
const ::CommonMsg::Header& PointCloudXYZIT::header() const {
  // @@protoc_insertion_point(field_get:SensorMsg.PointCloudXYZIT.header)
  return header_ != NULL ? *header_ : *default_instance_->header_;
}
::CommonMsg::Header* PointCloudXYZIT::mutable_header() {
  
  if (header_ == NULL) {
    header_ = new ::CommonMsg::Header;
  }
  // @@protoc_insertion_point(field_mutable:SensorMsg.PointCloudXYZIT.header)
  return header_;
}
::CommonMsg::Header* PointCloudXYZIT::release_header() {
  // @@protoc_insertion_point(field_release:SensorMsg.PointCloudXYZIT.header)
  
  ::CommonMsg::Header* temp = header_;
  header_ = NULL;
  return temp;
}
void PointCloudXYZIT::set_allocated_header(::CommonMsg::Header* header) {
  delete header_;
  header_ = header;
  if (header) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:SensorMsg.PointCloudXYZIT.header)
}

// optional int32 width = 2;
void PointCloudXYZIT::clear_width() {
  width_ = 0;
}
 ::google::protobuf::int32 PointCloudXYZIT::width() const {
  // @@protoc_insertion_point(field_get:SensorMsg.PointCloudXYZIT.width)
  return width_;
}
 void PointCloudXYZIT::set_width(::google::protobuf::int32 value) {
  
  width_ = value;
  // @@protoc_insertion_point(field_set:SensorMsg.PointCloudXYZIT.width)
}

// optional int32 height = 3;
void PointCloudXYZIT::clear_height() {
  height_ = 0;
}
 ::google::protobuf::int32 PointCloudXYZIT::height() const {
  // @@protoc_insertion_point(field_get:SensorMsg.PointCloudXYZIT.height)
  return height_;
}
 void PointCloudXYZIT::set_height(::google::protobuf::int32 value) {
  
  height_ = value;
  // @@protoc_insertion_point(field_set:SensorMsg.PointCloudXYZIT.height)
}

// optional bool is_dense = 4;
void PointCloudXYZIT::clear_is_dense() {
  is_dense_ = false;
}
 bool PointCloudXYZIT::is_dense() const {
  // @@protoc_insertion_point(field_get:SensorMsg.PointCloudXYZIT.is_dense)
  return is_dense_;
}
 void PointCloudXYZIT::set_is_dense(bool value) {
  
  is_dense_ = value;
  // @@protoc_insertion_point(field_set:SensorMsg.PointCloudXYZIT.is_dense)
}

// repeated .SensorMsg.PointXYZIT points = 5;
int PointCloudXYZIT::points_size() const {
  return points_.size();
}
void PointCloudXYZIT::clear_points() {
  points_.Clear();
}
const ::SensorMsg::PointXYZIT& PointCloudXYZIT::points(int index) const {
  // @@protoc_insertion_point(field_get:SensorMsg.PointCloudXYZIT.points)
  return points_.Get(index);
}
::SensorMsg::PointXYZIT* PointCloudXYZIT::mutable_points(int index) {
  // @@protoc_insertion_point(field_mutable:SensorMsg.PointCloudXYZIT.points)
  return points_.Mutable(index);
}
::SensorMsg::PointXYZIT* PointCloudXYZIT::add_points() {
  // @@protoc_insertion_point(field_add:SensorMsg.PointCloudXYZIT.points)
  return points_.Add();
}
::google::protobuf::RepeatedPtrField< ::SensorMsg::PointXYZIT >*
PointCloudXYZIT::mutable_points() {
  // @@protoc_insertion_point(field_mutable_list:SensorMsg.PointCloudXYZIT.points)
  return &points_;
}
const ::google::protobuf::RepeatedPtrField< ::SensorMsg::PointXYZIT >&
PointCloudXYZIT::points() const {
  // @@protoc_insertion_point(field_list:SensorMsg.PointCloudXYZIT.points)
  return points_;
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace SensorMsg

// @@protoc_insertion_point(global_scope)
